### PR TITLE
Ensure that CommitDelayIncrement is greater than TimeSpan.Zero

### LINKED ISSUE #530: If CommitDelayIncrement is set to zero, the Outbox dispatch message the MaximumCommitDuration is never reached
#### Description

On line 48, the `CommitDelayIncrement` is subtracted from the `remainingCommitDuration` to calculate the `newRemainingTime` which is passed to the retry dispatch message. If the `CommitDelayIncrement` is set to 0, then the `newRemainingTime` will never decrement, causing the `remainngCommitDuration` value to never reach 0. This prevents line 32 from ever being true. The message will never be consumed and will continue to retry indefinitely.

https://github.com/Particular/NServiceBus.TransactionalSession/blob/c00d617aba4a467283f120f0127fb366d6757d90/src/NServiceBus.TransactionalSession/TransactionalSessionDelayControlMessageBehavior.cs#L15-L67

#### Expected behavior

The `remainingCommitDuration` needs to be able to decrement.

#### Actual behavior

The dispatch message will never be consumed, and will instead be retried indefinitely.

#### Versions

TransactionalSession 3.4 and 4.0

### Steps to reproduce

Update the `Should_throw_exception_to_session_user` test to set `CommitDelayIncrement = TimeSpan.FromSeconds(0)`

https://github.com/Particular/NServiceBus.TransactionalSession/blob/c00d617aba4a467283f120f0127fb366d6757d90/src/NServiceBus.TransactionalSession.AcceptanceTests/When_outbox_commits_after_control_message.cs#L13-L36

### Relevant log output

```shell

```

#### Workarounds

Don't set CommitDelayIncrement = TimeSpan.FromSeconds(0).

#### Possible solutions

- Throw an exception or warning message when users attempt to set CommitDelayIncrement to 0.
- Update the setter so that it for `CommitDelayIncrement` to something like this `(value > TimeSpan.FromSeconds(1)) ? value : TimeSpan.FromSeconds(1);` and update the documentation.

### Backported to

- [4.0.1](https://github.com/Particular/NServiceBus.TransactionalSession/pull/536)
- [3.4.1](https://github.com/Particular/NServiceBus.TransactionalSession/pull/537)

### PR DESCRIPTION
**Pull request by hazel-bohon**
- Fixes #530 
- Added a check to ensure that the value of `CommitDelayIncrement` is greater than `TimeSpan.Zero`.
- Added unit test to verify the behavior.

### CODE REVIEW

File: src/NServiceBus.TransactionalSession/OpenSessionOptions.cs [hunk 1]
```diff
@@ -37,8 +37,12 @@ public abstract class OpenSessionOptions
     /// <summary>
     /// The time increment used to delay the commit of the transactional session when the outbox record is not yet in the storage.
     /// </summary>
-    /// <remarks>Defaults to <code>TimeSpan.FromSeconds(2)</code></remarks>
-    public TimeSpan CommitDelayIncrement { get; set; } = TimeSpan.FromSeconds(2);
+    /// <remarks>Defaults to <code>TimeSpan.FromSeconds(2)</code>. Value must be greater than <code>TimeSpan.Zero</code>.</remarks>
+    public TimeSpan CommitDelayIncrement
+    {
+        get;
+        set => field = (value > TimeSpan.Zero) ? value : throw new ArgumentOutOfRangeException(nameof(CommitDelayIncrement), "CommitDelayIncrement must be a non-negative TimeSpan.");
```
Comment (tamararivera) [inline src/NServiceBus.TransactionalSession/OpenSessionOptions.cs]: **Suggestion:** I think this message will make it clearer:
```suggestion
        set => field = (value > TimeSpan.Zero) ? value : throw new ArgumentOutOfRangeException(nameof(CommitDelayIncrement), "CommitDelayIncrement must be a positive TimeSpan.");
```
or 

```suggestion
        set => field = (value > TimeSpan.Zero) ? value : throw new ArgumentOutOfRangeException(nameof(CommitDelayIncrement), "CommitDelayIncrement must be a positive time interval.");
```

Comment (hazel-bohon) [reply src/NServiceBus.TransactionalSession/OpenSessionOptions.cs]: @tamararivera While "must be positive" definitely means that it cannot be zero, would it be better to be more explicit that the value must be greater than zero?
```suggestion
        set => field = (value > TimeSpan.Zero) ? value : throw new ArgumentOutOfRangeException(nameof(CommitDelayIncrement), "CommitDelayIncrement must be greater than TimeSpan.Zero.");
```

File: src/NServiceBus.TransactionalSession.Tests/OpenSessionOptionsTests.cs [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+    [TestCase(0)]
+    public void Should_throw_exception_when_commit_delay_increment_is_less_than_or_equal_to_zero(int commitDelayIncrement) =>
+        Assert.Throws<ArgumentOutOfRangeException>(() =>
+        {
+            var options = new CustomTestingPersistenceOpenSessionOptions
+            {
+                CommitDelayIncrement = TimeSpan.FromSeconds(commitDelayIncrement),
+                MaximumCommitDuration = TimeSpan.FromSeconds(8)
+            };
+        });
```
Comment (danielmarbach) [inline src/NServiceBus.TransactionalSession.Tests/OpenSessionOptionsTests.cs]:
```suggestion
        });

```

Should there also be a positive case that sets it right above the threshold, like `new Timespan(1)`?
